### ISSUE TITLE
Wrong path to plugin file path?

### ISSUE THREAD

**Issue by froger-me** [matomo-org/matomo-wordpress-plugin-examples#2]
In [https://github.com/matomo-org/matomo-wordpress-plugin-examples/blob/master/wordpress-plugin-adding-matomo-plugin/wordpress-plugin-adding-matomo-plugin.php:](https://github.com/matomo-org/matomo-wordpress-plugin-examples/blob/master/wordpress-plugin-adding-matomo-plugin/wordpress-plugin-adding-matomo-plugin.php:)

Shouldn't `matomo_add_plugin( __DIR__ . '/plugins/MyCustomPlugin', __FILE__ );` be changed to `matomo_add_plugin( __DIR__ . '/plugins/MyCustomPlugin', __DIR__ . '/plugins/MyCustomPlugin/MyCustomPlugin.php' );` or similar?

With the original code, I get:

`The following plugins are not compatible with Matomo 4.5.0 and could not be loaded:` **`MyCustomPlugin`**`.`

in Matomo Administration view. 

Looking at the source code of [https://plugins.matomo.org/DiagnosticsExtended](https://plugins.matomo.org/DiagnosticsExtended) using `__FILE__` works because the class is defined in the main plugin file.

**Comment by tsteur** [comment]
Yes it works when the code is in the main plugin file. Indeed you need to adjust the parameters otherwise. I've created https://github.com/matomo-org/matomo-wordpress-plugin-examples/pull/3 for now not sure if this makes it maybe slightly more clear?

Ideally we would otherwise move the widget related code in a separate file and that might make it easier maybe.

**Comment by froger-me** [comment]
I did manage to make it work, looking at other examples of plugin ; originally, I somehow expected the example to work out of the box, not being familiar with how classes are looked up and everything is hooked. I'm definitely learning digging code & documentation, so that's not impossible to get around - mostly I'm thinking about expectations set by an example :).

**Comment by tsteur** [comment]
Great, thanks for creating these issues. We very appreciate this @froger-me  👍

**Comment by froger-me** [comment]
Unsubscribed to avoid spam
